/**
 * Hook Scripts Generator
 *
 * Generates shell scripts for OpenClaw hooks:
 * - command-new: final observation sweep on session end
 * - gateway-startup: generate OBSERVATIONS.md
 *
 * These are generated as files — NOT installed automatically.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Generate the command-new hook script content.
 * @param {Object} options
 * @param {string} options.daemonScript - Path to daemon.js
 * @param {string} options.transcriptsDir - Transcripts directory
 * @param {string} options.vaultDir - Vault directory
 * @returns {string}
 */
export function commandNewHookScript(options) {
  return `#!/bin/bash
# OpenClaw hook: command-new / command-reset
# Triggers a final observation sweep on session end.
# Generated by Cortex observer — do not edit manually.
# Install to: ~/.openclaw/hooks/command-new/cortex-sweep.sh

DAEMON_SCRIPT="${options.daemonScript}"
TRANSCRIPTS="${options.transcriptsDir}"
VAULT="${options.vaultDir}"

# Run a one-shot extraction pass on any unprocessed content
node "$DAEMON_SCRIPT" --transcripts "$TRANSCRIPTS" --vault "$VAULT" --once 2>/tmp/cortex-sweep.log

exit 0
`;
}

/**
 * Generate the gateway-startup hook script content.
 * @param {Object} options
 * @param {string} options.observationsScript - Path to observations.js runner
 * @param {string} options.vaultDir - Vault directory
 * @param {string} options.workspaceDir - Workspace directory for HANDOFF.md
 * @param {string} options.outputPath - Path to write OBSERVATIONS.md
 * @returns {string}
 */
export function gatewayStartupHookScript(options) {
  return `#!/bin/bash
# OpenClaw hook: gateway-startup
# Generates OBSERVATIONS.md for the next session.
# Generated by Cortex observer — do not edit manually.
# Install to: ~/.openclaw/hooks/gateway-startup/cortex-observations.sh

OBSERVATIONS_SCRIPT="${options.observationsScript}"
VAULT="${options.vaultDir}"
WORKSPACE="${options.workspaceDir}"
OUTPUT="${options.outputPath}"

node "$OBSERVATIONS_SCRIPT" --vault "$VAULT" --workspace "$WORKSPACE" --output "$OUTPUT" 2>/tmp/cortex-observations.log

exit 0
`;
}

/**
 * Write hook scripts to an output directory.
 * @param {string} outputDir - Directory to write hook scripts
 * @param {Object} options - Options for both hooks
 * @returns {Promise<string[]>} Paths of generated files
 */
export async function generateHooks(outputDir, options) {
  await mkdir(outputDir, { recursive: true });

  const commandNewPath = join(outputDir, 'cortex-sweep.sh');
  const startupPath = join(outputDir, 'cortex-observations.sh');

  await writeFile(commandNewPath, commandNewHookScript(options), { mode: 0o755 });
  await writeFile(startupPath, gatewayStartupHookScript(options), { mode: 0o755 });

  console.log(`[hooks] Generated ${commandNewPath}`);
  console.log(`[hooks] Generated ${startupPath}`);

  return [commandNewPath, startupPath];
}
